//
//  GeneratedPluginRegistrant.swift
//  Runner
//
//  This file is auto-generated by Flutter tooling.
//  DO NOT EDIT — regenerated by running `flutter pub get`.
//

import Flutter
import UIKit

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  // Flutter camera plugin
  // google_mlkit_face_detection plugin
  // permission_handler plugin
  // tflite_flutter plugin
  // All registered automatically by Flutter build tools
}
